// This file is generated by Expo Router

export default function NotFoundScreen() {
  return (
    <div style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <h1>404 - Page Not Found</h1>
    </div>
  );
}
